version: "3.8"

services:
  app:
    build: .docker/php
    volumes:
      - ./:/app
    env_file:
      - .env
    command: composer install
    networks:
      - bbwe

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bbwe

networks:
  bbwe: